# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
                ('comment_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-comment_created_date'],
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comments_post',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
